[project]
name = "document-proofreader"
version = "0.1.0"
description = "AI-powered document proofreading application using GPT-4"
requires-python = ">=3.11"
dependencies = [
    "docx>=0.2.4",
    "openai>=1.88.0",
    "python-docx>=1.2.0",
    "streamlit>=1.46.0",
    "tiktoken>=0.9.0",
]
